In [1]:
import numpy as np

In [2]:
# 本来csvなどから読み込む
X = np.array([
    [1,2,3],
[1,2,5],
[1,3,4],
[1,5,9]])

In [3]:
print (X)

[[1 2 3]
 [1 2 5]
 [1 3 4]
 [1 5 9]]


In [4]:
y = np.array([
    [1],
    [5],
    [6],
    [8]
])
print (y)

[[1]
 [5]
 [6]
 [8]]


In [5]:
# step1
XtX= np.dot(X.T,X)
print(XtX)

[[  4  12  21]
 [ 12  42  73]
 [ 21  73 131]]


In [6]:
# step2
XtX_inv = np.linalg.inv(XtX)
print(XtX_inv)

[[ 1.76530612 -0.39795918 -0.06122449]
 [-0.39795918  0.84693878 -0.40816327]
 [-0.06122449 -0.40816327  0.24489796]]


In [7]:
# step 3
Xty = np.dot(X.T,y)
print(Xty)

[[ 20]
 [ 70]
 [124]]


In [8]:
#Step4
ans = np.dot(XtX_inv,Xty)
print(ans)

[[-0.14285714]
 [ 0.71428571]
 [ 0.57142857]]
