In [1]:
import numpy as np

In [5]:
# 変数定義
# 本来csvなどから読み込む
X = np.array([
    [1,2,3],
[1,2,5],
[1,3,4],
[1,5,9]])

In [6]:
print(X)

[[1 2 3]
 [1 2 5]
 [1 3 4]
 [1 5 9]]


In [7]:
y = np.array([
    [1],
    [5],
    [6],
    [8]
])
print (y)

[[1]
 [5]
 [6]
 [8]]


In [8]:
from sklearn.linear_model import LinearRegression

In [9]:
# モデルの宣言
model = LinearRegression()

In [10]:
# モデルの学習 <- パラメータの調整
model.fit(X,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [11]:
# 調整後のパラメータ
model.coef_

array([[0.        , 0.71428571, 0.57142857]])

In [16]:
# 切片
model.intercept_

array([-0.14285714])

In [13]:
# 予測精度 <- 決定係数
model.score(X,y)

0.6923076923076923

In [14]:
# 予測値の計算
x = np.array([[1,2,3]])

In [15]:
y_pred = model.predict(x)
print (y_pred)

[[3.]]
