# 行列演算の基礎

- ベクトルの定義
-  行列の定義
-  転機
-  逆光列
-  行列き

In [8]:
import numpy as np

In [9]:
x = np.array([[1],[2],[3]])
print(x)

[[1]
 [2]
 [3]]


In [10]:
X = np.array([[1,2,3],[3,4,666]])

In [11]:
print(X)

[[  1   2   3]
 [  3   4 666]]


In [12]:
Xt = X.T

In [13]:
print(Xt)

[[  1   3]
 [  2   4]
 [  3 666]]


In [14]:
# 逆行列
# linear algebra 線形代数

In [15]:
X_inv = np.linalg.inv(x)

LinAlgError: Last 2 dimensions of the array must be square

In [16]:
print(X_inv)

NameError: name 'X_inv' is not defined

In [17]:
# 行列積

In [18]:
XX_inv = np.dot(X,X_inv)

NameError: name 'X_inv' is not defined

In [19]:
print(XX_inv)

NameError: name 'XX_inv' is not defined

# よくある間違い

In [20]:
x = np.array([[1,2,3]])
x

array([[1, 2, 3]])

In [21]:
x.T

array([[1],
       [2],
       [3]])

In [22]:
# Numpyでよく使う処理

In [23]:
X

array([[  1,   2,   3],
       [  3,   4, 666]])

In [24]:
row,cal =X.shape

In [25]:
row

2

In [26]:
cal

3

In [27]:
for x in X:
    print ('--')
    print(x)

--
[1 2 3]
--
[  3   4 666]


# 演習問題

-  一行目はダミーで１を入れる

In [28]:
# 本来csvなどから読み込む
X = np.array([
    [1,2,3],
[1,2,5],
[1,3,4],
[1,5,9]])

In [29]:
print (X)

[[1 2 3]
 [1 2 5]
 [1 3 4]
 [1 5 9]]


In [30]:
y = np.array([
    [1],
    [5],
    [6],
    [8]
])
print (y)

[[1]
 [5]
 [6]
 [8]]


In [31]:
# step1
XtX= np.dot(X.T,X)
print(XtX)

[[  4  12  21]
 [ 12  42  73]
 [ 21  73 131]]


In [32]:
# step2

In [33]:
XtX_inv = np.linalg.inv(XtX)
print(XtX_inv)

[[ 1.76530612 -0.39795918 -0.06122449]
 [-0.39795918  0.84693878 -0.40816327]
 [-0.06122449 -0.40816327  0.24489796]]


In [34]:
# step 3

In [35]:
Xty = np.dot(X.T,y)
print(Xty)

[[ 20]
 [ 70]
 [124]]


In [36]:
#Step4

In [37]:
ans = np.dot(XtX_inv,Xty)
print(ans)

[[-0.14285714]
 [ 0.71428571]
 [ 0.57142857]]


In [38]:
from sklearn.linear_model import LinearRegression

In [39]:
# モデルの宣言
model = LinearRegression()

In [40]:
# モデルの学習 <- パラメータの調整
model.fit(X,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [42]:
# 調整後のパラメータ
model.coef_

array([[0.        , 0.71428571, 0.57142857]])

In [43]:
model.intercept_

array([-0.14285714])

In [50]:
# 予測精度 <- 決定係数
model.score(X,y)

0.6923076923076923

In [51]:
# 予測値の計算
x = np.array([[1,2,3]])

In [55]:
y_pred = model.predict(x)
print (y_pred)

[[3.]]
